UNCONFIGURED_COMMENT = "未配置中文注释"


TABLE_COMMENTS: dict[str, str] = {
    "users": "用户账户表，保存用户身份、资料、角色和统计计数。",
    "user_follows": "用户关注关系表，记录关注人与被关注人的关系。",
    "fan_circles": "球迷圈表，保存俱乐部圈子基础信息和圈主。",
    "posts": "帖子表，保存球迷圈内发布的主题内容和互动计数。",
    "post_tags": "帖子标签表，保存帖子关联的标签。",
    "post_polls": "帖子投票表，保存帖子关联的投票问题。",
    "post_poll_options": "投票选项表，保存每个投票问题下的可选项。",
    "post_poll_votes": "投票记录表，记录用户对投票选项的选择。",
    "comments": "评论表，保存帖子评论、回复层级和互动计数。",
    "user_events": "用户事件表，记录用户维度的行为事件。",
    "fan_circle_events": "球迷圈事件表，记录圈子维度的行为事件。",
    "post_events": "帖子事件表，记录帖子和评论维度的行为事件。",
    "system_settings": "系统设置表，保存可在线调整的系统配置。",
    "ai_database_facts": "AI 数据库事实表，保存用于 RAG 检索的结构、注释和样例事实。",
    "ai_database_fact_fts": "AI 数据库事实全文索引表，用于按问题检索相关事实。",
    "ai_chat_sessions": "AI 聊天会话表，保存数据库 AI 助手的会话归属和标题。",
    "ai_chat_messages": "AI 聊天消息表，保存用户和助手的对话消息。",
    "ai_chat_events": "AI 聊天埋点表，记录检索、调用模型和错误等摘要指标。",
    "ai_code_facts": "AI 代码事实表，保存用于 RAG 检索的项目代码片段。",
    "ai_code_fact_fts": "AI 代码事实全文索引表，用于按问题检索相关代码片段。",
    "ai_code_chat_sessions": "AI 代码问答会话表，保存代码 AI 助手的会话归属和标题。",
    "ai_code_chat_messages": "AI 代码问答消息表，保存用户和助手的代码问答消息。",
    "ai_code_chat_events": "AI 代码问答埋点表，记录检索、调用模型和错误等摘要指标。",
}


COLUMN_COMMENTS: dict[str, dict[str, str]] = {
    "users": {
        "id": "用户主键 ID。",
        "username": "登录用户名，唯一。",
        "nickname": "用户显示昵称。",
        "password_hash": "密码哈希值。",
        "role": "用户角色，区分超级管理员、圈主和普通用户。",
        "avatar_url": "用户头像资源地址。",
        "bio": "用户个人简介。",
        "following_count": "当前用户关注的人数。",
        "followers_count": "当前用户的粉丝数。",
        "total_likes_received": "用户发布内容累计收到的点赞数。",
        "total_dislikes_received": "用户发布内容累计收到的点踩数。",
        "is_active": "账号是否启用，1 表示启用。",
        "created_at": "用户创建时间。",
        "updated_at": "用户最近更新时间。",
    },
    "user_follows": {
        "follower_user_id": "发起关注的用户 ID。",
        "followed_user_id": "被关注的用户 ID。",
        "created_at": "关注关系创建时间。",
    },
    "fan_circles": {
        "id": "球迷圈主键 ID。",
        "club_name": "俱乐部名称。",
        "board_name": "圈子版块名称。",
        "league_name": "所属联赛名称。",
        "logo_url": "俱乐部 Logo 资源地址。",
        "owner_user_id": "圈主用户 ID，可为空。",
        "description": "球迷圈简介。",
        "post_count": "圈子内帖子数量。",
        "follower_count": "圈子关注人数。",
        "created_at": "圈子创建时间。",
        "updated_at": "圈子最近更新时间。",
    },
    "posts": {
        "id": "帖子主键 ID。",
        "fan_circle_id": "帖子所属球迷圈 ID。",
        "author_user_id": "帖子作者用户 ID。",
        "title": "帖子标题。",
        "content": "帖子正文内容。",
        "category": "帖子分类。",
        "like_count": "帖子点赞数。",
        "dislike_count": "帖子点踩数。",
        "comment_count": "帖子评论数。",
        "has_poll": "是否包含投票，1 表示包含。",
        "is_pinned": "是否置顶，1 表示置顶。",
        "is_locked": "是否锁定，1 表示锁定。",
        "created_at": "帖子创建时间。",
        "updated_at": "帖子最近更新时间。",
    },
    "post_tags": {
        "id": "标签记录主键 ID。",
        "post_id": "关联帖子 ID。",
        "tag_name": "标签名称。",
    },
    "post_polls": {
        "id": "投票主键 ID。",
        "post_id": "关联帖子 ID，唯一。",
        "question": "投票问题。",
        "allow_multiple": "是否允许多选，1 表示允许。",
        "expires_at": "投票截止时间，可为空。",
    },
    "post_poll_options": {
        "id": "投票选项主键 ID。",
        "poll_id": "所属投票 ID。",
        "option_text": "选项文本。",
        "vote_count": "该选项累计票数。",
    },
    "post_poll_votes": {
        "id": "投票记录主键 ID。",
        "poll_id": "所属投票 ID。",
        "option_id": "被选择的投票选项 ID。",
        "user_id": "投票用户 ID。",
        "created_at": "投票时间。",
    },
    "comments": {
        "id": "评论主键 ID。",
        "post_id": "评论所属帖子 ID。",
        "author_user_id": "评论作者用户 ID。",
        "parent_comment_id": "父评论 ID，顶级评论为空。",
        "content": "评论正文内容。",
        "depth": "评论嵌套深度。",
        "path": "评论树排序路径。",
        "like_count": "评论点赞数。",
        "dislike_count": "评论点踩数。",
        "created_at": "评论创建时间。",
        "updated_at": "评论最近更新时间。",
    },
    "user_events": {
        "id": "用户事件主键 ID。",
        "actor_user_id": "触发事件的用户 ID，可为空。",
        "target_user_id": "事件目标用户 ID，可为空。",
        "event_type": "事件类型。",
        "metadata_json": "事件扩展信息 JSON。",
        "created_at": "事件发生时间。",
    },
    "fan_circle_events": {
        "id": "球迷圈事件主键 ID。",
        "actor_user_id": "触发事件的用户 ID，可为空。",
        "fan_circle_id": "事件关联球迷圈 ID。",
        "event_type": "事件类型。",
        "metadata_json": "事件扩展信息 JSON。",
        "created_at": "事件发生时间。",
    },
    "post_events": {
        "id": "帖子事件主键 ID。",
        "actor_user_id": "触发事件的用户 ID，可为空。",
        "post_id": "事件关联帖子 ID。",
        "comment_id": "事件关联评论 ID，可为空。",
        "event_type": "事件类型。",
        "metadata_json": "事件扩展信息 JSON。",
        "created_at": "事件发生时间。",
    },
    "system_settings": {
        "key": "配置项键名。",
        "value": "配置项取值。",
        "updated_at": "配置最近更新时间。",
    },
    "ai_database_facts": {
        "id": "AI 事实主键 ID。",
        "source_database_path": "事实来源数据库相对路径。",
        "source_table_name": "事实来源表名，可为空。",
        "source_column_name": "事实来源字段名，可为空。",
        "fact_type": "事实类型，例如数据库、表、字段、索引、外键或样例行。",
        "title": "事实标题，用于检索和引用展示。",
        "content": "事实正文，用于 RAG 上下文。",
        "metadata_json": "事实扩展元数据 JSON。",
        "content_hash": "事实内容哈希，用于去重。",
        "generated_at": "事实生成时间。",
        "updated_at": "事实最近更新时间。",
    },
    "ai_database_fact_fts": {
        "title": "全文索引中的事实标题。",
        "content": "全文索引中的事实正文。",
    },
    "ai_chat_sessions": {
        "id": "AI 聊天会话主键 ID。",
        "public_id": "对前端暴露的会话 ID。",
        "owner_user_id": "登录用户 ID，匿名会话为空。",
        "client_id_hash": "匿名客户端 ID 的哈希值，登录会话可为空。",
        "title": "会话标题。",
        "created_at": "会话创建时间。",
        "updated_at": "会话最近更新时间。",
    },
    "ai_chat_messages": {
        "id": "AI 聊天消息主键 ID。",
        "session_id": "消息所属会话 ID。",
        "role": "消息角色，用户或助手。",
        "content": "消息正文。",
        "retrieved_fact_ids_json": "该消息关联的检索事实 ID 列表 JSON。",
        "thinking_enabled": "本轮消息是否开启深度思考，1 表示开启。",
        "thinking_content": "模型返回的深度思考内容。",
        "input_token_count": "本轮模型调用输入 token 数。",
        "output_token_count": "本轮模型调用输出 token 数。",
        "created_at": "消息创建时间。",
    },
    "ai_chat_events": {
        "id": "AI 聊天埋点主键 ID。",
        "event_type": "埋点事件类型。",
        "session_id": "事件关联会话 ID，可为空。",
        "message_id": "事件关联消息 ID，可为空。",
        "actor_user_id": "触发事件的登录用户 ID，可为空。",
        "model": "调用或检查的模型名称。",
        "retrieved_fact_ids_json": "命中的事实 ID 列表 JSON。",
        "retrieved_fact_count": "命中的事实数量。",
        "thinking_enabled": "本次调用是否开启深度思考，1 表示开启。",
        "input_token_count": "本次调用输入 token 数。",
        "output_token_count": "本次调用输出 token 数。",
        "duration_ms": "事件耗时毫秒数。",
        "status": "事件状态，例如 success 或 error。",
        "error_message": "错误摘要，可为空。",
        "created_at": "事件发生时间。",
    },
    "ai_code_facts": {
        "id": "AI 代码事实主键 ID。",
        "source_file_path": "代码片段来源文件相对路径。",
        "language": "来源文件语言或文件类型。",
        "start_line": "代码片段起始行号。",
        "end_line": "代码片段结束行号。",
        "title": "代码事实标题，用于检索和引用展示。",
        "content": "代码片段正文，用于 RAG 上下文。",
        "metadata_json": "代码事实扩展元数据 JSON。",
        "content_hash": "代码事实内容哈希，用于去重。",
        "generated_at": "代码事实生成时间。",
        "updated_at": "代码事实最近更新时间。",
    },
    "ai_code_fact_fts": {
        "source_file_path": "全文索引中的来源文件路径。",
        "title": "全文索引中的代码事实标题。",
        "content": "全文索引中的代码片段正文。",
    },
    "ai_code_chat_sessions": {
        "id": "AI 代码问答会话主键 ID。",
        "public_id": "对前端暴露的会话 ID。",
        "owner_user_id": "登录用户 ID，匿名会话为空。",
        "client_id_hash": "匿名客户端 ID 的哈希值，登录会话可为空。",
        "title": "会话标题。",
        "created_at": "会话创建时间。",
        "updated_at": "会话最近更新时间。",
    },
    "ai_code_chat_messages": {
        "id": "AI 代码问答消息主键 ID。",
        "session_id": "消息所属会话 ID。",
        "role": "消息角色，用户或助手。",
        "content": "消息正文。",
        "retrieved_fact_ids_json": "该消息关联的检索事实 ID 列表 JSON。",
        "thinking_enabled": "本轮消息是否开启深度思考，1 表示开启。",
        "thinking_content": "模型返回的深度思考内容。",
        "input_token_count": "本轮模型调用输入 token 数。",
        "output_token_count": "本轮模型调用输出 token 数。",
        "created_at": "消息创建时间。",
    },
    "ai_code_chat_events": {
        "id": "AI 代码问答埋点主键 ID。",
        "event_type": "埋点事件类型。",
        "session_id": "事件关联会话 ID，可为空。",
        "message_id": "事件关联消息 ID，可为空。",
        "actor_user_id": "触发事件的登录用户 ID，可为空。",
        "model": "调用或检查的模型名称。",
        "retrieved_fact_ids_json": "命中的事实 ID 列表 JSON。",
        "retrieved_fact_count": "命中的事实数量。",
        "thinking_enabled": "本次调用是否开启深度思考，1 表示开启。",
        "input_token_count": "本次调用输入 token 数。",
        "output_token_count": "本次调用输出 token 数。",
        "duration_ms": "事件耗时毫秒数。",
        "status": "事件状态，例如 success 或 error。",
        "error_message": "错误摘要，可为空。",
        "created_at": "事件发生时间。",
    },
}


def get_table_comment(table_name: str) -> str:
    return TABLE_COMMENTS.get(table_name, UNCONFIGURED_COMMENT)


def get_column_comment(table_name: str, column_name: str) -> str:
    return COLUMN_COMMENTS.get(table_name, {}).get(column_name, UNCONFIGURED_COMMENT)
